# Please insert new items alphabetically.

editorial-fe:
  members:
    - sstaton

  channel:
    "#editorial_fe_reviews"

  exclude_titles:
    - "[DO NOT MERGE]"
    - DO NOT MERGE
    - WIP


  quotes:
    - If it’s gonna take more than 30 minutes, or it needs deploying - write a card for it and chat to the Product Manager.
    - Try to pair when possible.
    - Be considerate to remote workers and follow the Working from home practices https://gov-uk.atlassian.net/wiki/x/Bz_5Bw and https://gov-uk.atlassian.net/wiki/display/CT/Working+from+home+ideas
    - Who's organising the next team lunch?
    - If you're not well, don't come in to the office. And get some rest!
    - Set your Slack status to away or do not disturb so people know whether they can disturb you.
    - Has your story got points?
    - Don't forget to assign your face to a card and PR if you're working on it or reviewing.
    - Don't forget the Jabra and fisheye lens if you're dialing in people!
    - If Hangouts is being flaky, try Slack calls or appear.in!
    - I AM VENGEANCE! I AM THE NIGHT! I AM BATMAN! :batsignal:
